# Wialon 
    көліктердің ақпараттары бар 
    көліктер, км, точка А точка Б, уакыттары

In [92]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [1]:
 #бұл код wialon-нан көліктер туралы мәліметті алады
from wialon import Wialon         
from wialon import WialonError
import json
try:
    wialon_api = Wialon()
    result = wialon_api.token_login(token='070b1b14f585912b9b172d65147bea8a35F9FEBE0D11F7F8D0436964F7A299DFF8E5E938')
    wialon_api.sid = result['eid']

    params = {
        "spec": {
            "itemsType": "avl_unit",
            "propName": "sys_name",
            "propValueMask": "*",
            "sortType": "sys_name"
        },
        "force": 1,
        "flags": 1,
        "from": 0,
        "to": 0
    }
    result = wialon_api.core_search_items(**params)

    wialon_api.core_logout()

    print (result)
except WialonError as e:
    print (e)

{'searchSpec': {'itemsType': 'avl_unit', 'propName': 'sys_name', 'propValueMask': '*', 'sortType': 'sys_name', 'propType': '', 'or_logic': '0'}, 'dataFlags': 1, 'totalItemsCount': 109, 'indexFrom': 0, 'indexTo': 0, 'items': [{'nm': '01KG1187M SUZUKI Мурат', 'cls': 2, 'id': 20556226, 'mu': 0, 'uacl': 71332791}, {'nm': '01KG1219M LADA Едил', 'cls': 2, 'id': 20556225, 'mu': 0, 'uacl': 71332791}, {'nm': '01KG1230M FORESTER Ешимов Н.', 'cls': 2, 'id': 20556222, 'mu': 0, 'uacl': 71332791}, {'nm': '01KG1346M LADA', 'cls': 2, 'id': 20556221, 'mu': 0, 'uacl': 71332791}, {'nm': '012DL02 Largus Бакытжан Караганда', 'cls': 2, 'id': 20556220, 'mu': 0, 'uacl': 71332791}, {'nm': '017RD02 CAMRY 50 Махмуд водитель', 'cls': 2, 'id': 20556219, 'mu': 0, 'uacl': 71332791}, {'nm': '028JD02 Terrano Иван К.', 'cls': 2, 'id': 22702206, 'mu': 0, 'uacl': 71332791}, {'nm': '031DL02 Lada Стас Кокшетау', 'cls': 2, 'id': 20556217, 'mu': 0, 'uacl': 71332791}, {'nm': '031JD02 Terrano Самохин А.', 'cls': 2, 'id': 22702241, 'mu': 0, 'uacl': 71332791}, {'nm': '033DL02 Largus Продажа', 'cls': 2, 'id': 20556215, 'mu': 0, 'uacl': 71332791}, {'nm': '036JD02 X-Trail Серик Нурмакин Кст', 'cls': 2, 'id': 22702230, 'mu': 0, 'uacl': 71332791}, {'nm': '038JD02 X-Trail Резерв', 'cls': 2, 'id': 20556192, 'mu': 0, 'uacl': 71332791}, {'nm': '039JD02 X-Trail Константин Н.', 'cls': 2, 'id': 22702139, 'mu': 0, 'uacl': 71332791}, {'nm': '041JD02 Terrano Андрей О. Кст', 'cls': 2, 'id': 22702135, 'mu': 0, 'uacl': 71332791}, {'nm': '042JD02 Terrano Нурсултан', 'cls': 2, 'id': 22702175, 'mu': 0, 'uacl': 71332791}, {'nm': '043JD02 Terrano Адилет Т.', 'cls': 2, 'id': 22702146, 'mu': 0, 'uacl': 71332791}, {'nm': '044JD02 X-Trail Манжос', 'cls': 2, 'id': 22702162, 'mu': 0, 'uacl': 71332791}, {'nm': '045JD02 X-Trail Нурбосын Шымкент', 'cls': 2, 'id': 22702154, 'mu': 0, 'uacl': 71332791}, {'nm': '046JD02 X-Trail Владимир В.', 'cls': 2, 'id': 22702182, 'mu': 0, 'uacl': 71332791}, {'nm': '047JD02 X-Trail Асылжан Шымкент', 'cls': 2, 'id': 22702170, 'mu': 0, 'uacl': 71332791}, {'nm': '048JD02 X-Trail Предыбайло А.', 'cls': 2, 'id': 20556213, 'mu': 0, 'uacl': 71332791}, {'nm': '049JD02 X-Trail Марат К.', 'cls': 2, 'id': 22702211, 'mu': 0, 'uacl': 71332791}, {'nm': '051JD02 X-Trail Ерсаин Талдык', 'cls': 2, 'id': 20556158, 'mu': 0, 'uacl': 71332791}, {'nm': '070BB02 Duster Кызылорда', 'cls': 2, 'id': 20556212, 'mu': 0, 'uacl': 71332791}, {'nm': '086JD02 Terrano Ануарбеков М.', 'cls': 2, 'id': 22968615, 'mu': 0, 'uacl': 71332791}, {'nm': '089JD02 Terrano Диас Ж.', 'cls': 2, 'id': 23119160, 'mu': 0, 'uacl': 71332791}, {'nm': '091YD02 Forester Данильчук', 'cls': 2, 'id': 20556210, 'mu': 0, 'uacl': 71332791}, {'nm': '095JD02 Terrano Тенес И.', 'cls': 2, 'id': 23119207, 'mu': 0, 'uacl': 71332791}, {'nm': '095YD02 Forester Болатбек', 'cls': 2, 'id': 20556209, 'mu': 0, 'uacl': 71332791}, {'nm': '097JD02 Terrano Ержан Уральск', 'cls': 2, 'id': 23119294, 'mu': 0, 'uacl': 71332791}, {'nm': '098JD02 Terrano Ильяс Х.', 'cls': 2, 'id': 23119194, 'mu': 0, 'uacl': 71332791}, {'nm': '098YD02 Forester Ерик', 'cls': 2, 'id': 20556208, 'mu': 0, 'uacl': 71332791}, {'nm': '101CE02 CAMRY 50 Актилек', 'cls': 2, 'id': 20556207, 'mu': 0, 'uacl': 71332791}, {'nm': '123YD02 FORESTER Арыстан', 'cls': 2, 'id': 20556204, 'mu': 0, 'uacl': 71332791}, {'nm': '124YD02 LADA Берик Урджар', 'cls': 2, 'id': 20556203, 'mu': 0, 'uacl': 71332791}, {'nm': '132YD02 Largus Ернар Петропавл', 'cls': 2, 'id': 20556202, 'mu': 0, 'uacl': 71332791}, {'nm': '133YD02 Forester Марат М.', 'cls': 2, 'id': 20556201, 'mu': 0, 'uacl': 71332791}, {'nm': '141LV02 X trail Нуржан Даутов', 'cls': 2, 'id': 22155670, 'mu': 0, 'uacl': 71332791}, {'nm': '161LV02 X trail Виктор Галкин', 'cls': 2, 'id': 22417870, 'mu': 0, 'uacl': 71332791}, {'nm': '171YL02 Нуржан Э. Бишкек', 'cls': 2, 'id': 20556198, 'mu': 0, 'uacl': 71332791}, {'nm': '191CI02 Lada Мирхат М.', 'cls': 2, 'id': 20556187, 'mu': 0, 'uacl': 71332791}, {'nm': '196LP02 Lada Данияр Актобе', 'cls': 2, 'id': 20556161, 'mu': 0, 'uacl': 71332791}, {'nm': '216BZ02 SPRINTER Мирхат', 'cls': 2, 'id': 20556197, 'mu': 0, 'uacl': 71332791}, {'nm': '227CK02 Lada Улан', 'cls': 2, 'id': 20556196, 'mu': 0, 'uacl': 71332791}, {'nm': '242YD02 Forester Берик Уральск', 'cls': 2, 'id': 21151684, 'mu': 0, 'uacl': 71332791}, {'nm': '264ZV02 Forester Нурберген Ж. Актобе', 'cls': 2, 'id': 23119270, 'mu': 0, 'uacl': 71332791}, {'nm': '265ZV02 Forester Резерв', 'cls': 2, 'id': 23119231, 'mu': 0, 'uacl': 71332791}, {'nm': '266ZV02 Forester Эдиль', 'cls': 2, 'id': 23119250, 'mu': 0, 'uacl': 71332791}, {'nm': '278YP02 Lada Нурсултан Саркант', 'cls': 2, 'id': 20556164, 'mu': 0, 'uacl': 71332791}, {'nm': '287YP02 Lada Даулет К. Алмата', 'cls': 2, 'id': 20556166, 'mu': 0, 'uacl': 71332791}, {'nm': '323LK02 Toyota Жанна Николаевна', 'cls': 2, 'id': 21681931, 'mu': 0, 'uacl': 71332791}, {'nm': '409AV02 OUTLANDER', 'cls': 2, 'id': 20556188, 'mu': 0, 'uacl': 71332791}, {'nm': '422YT02 Forester Виктор П.', 'cls': 2, 'id': 20556199, 'mu': 0, 'uacl': 71332791}, {'nm': '455DP02', 'cls': 2, 'id': 20556182, 'mu': 0, 'uacl': 71332791}, {'nm': '490DK02 Largus Арман Аст', 'cls': 2, 'id': 20556178, 'mu': 0, 'uacl': 71332791}, {'nm': '491YT02 Lada Акылбек Уральск', 'cls': 2, 'id': 20556190, 'mu': 0, 'uacl': 71332791}, {'nm': '630YC02 LADA Танат Кокшетау', 'cls': 2, 'id': 20556174, 'mu': 0, 'uacl': 71332791}, {'nm': '670DK02 Largus', 'cls': 2, 'id': 20556171, 'mu': 0, 'uacl': 71332791}, {'nm': '680HE02 Forester Алмас С.', 'cls': 2, 'id': 20556170, 'mu': 0, 'uacl': 71332791}, {'nm': '715DL02 Corolla Гульмира', 'cls': 2, 'id': 20556169, 'mu': 0, 'uacl': 71332791}, {'nm': '720AJ02 Terrano Коблан', 'cls': 2, 'id': 22702115, 'mu': 0, 'uacl': 71332791}, {'nm': '727DL02 COROLLA Гульжан', 'cls': 2, 'id': 20556168, 'mu': 0, 'uacl': 71332791}, {'nm': '727RR02 Arkana Алмас К.', 'cls': 2, 'id': 20556193, 'mu': 0, 'uacl': 71332791}, {'nm': '739AJ02 Terrano Эдиль Алматы', 'cls': 2, 'id': 20556159, 'mu': 0, 'uacl': 71332791}, {'nm': '740AJ02 Шынгыс Актобе', 'cls': 2, 'id': 20773569, 'mu': 0, 'uacl': 71332791}, {'nm': '741AJ02 JAC N120 Павел Кокшетау', 'cls': 2, 'id': 24406144, 'mu': 0, 'uacl': 71332791}, {'nm': '741BJ02 Duster Рахманов И. Кокш', 'cls': 2, 'id': 25178501, 'mu': 0, 'uacl': 71332791}, {'nm': '742BJ02 Duster Бориленко А. Усть-Кам', 'cls': 2, 'id': 25178490, 'mu': 0, 'uacl': 71332791}, {'nm': '743AJ02 Terrano Сайлау Аст', 'cls': 2, 'id': 20556176, 'mu': 0, 'uacl': 71332791}, {'nm': '744AJ02 Lada Дамежан', 'cls': 2, 'id': 20556183, 'mu': 0, 'uacl': 71332791}, {'nm': '745BJ02 Duster Жансерик Костанай', 'cls': 2, 'id': 25178452, 'mu': 0, 'uacl': 71332791}, {'nm': '746BJ02 Duster Нурберген Али Кызылорда', 'cls': 2, 'id': 25178617, 'mu': 0, 'uacl': 71332791}, {'nm': '747BJ02 Outback Володя Чижаковский', 'cls': 2, 'id': 25178386, 'mu': 0, 'uacl': 71332791}, {'nm': '748BJ02 Renault Duster Аслан А.', 'cls': 2, 'id': 20556177, 'mu': 0, 'uacl': 71332791}, {'nm': '749BJ02 JAC T6 Кайрат Усть-Кам', 'cls': 2, 'id': 25178551, 'mu': 0, 'uacl': 71332791}, {'nm': '750BJ02 JAC T6 Бауржан Петропавл', 'cls': 2, 'id': 25178628, 'mu': 0, 'uacl': 71332791}, {'nm': '751BJ02 JAC T6 Салман', 'cls': 2, 'id': 25178663, 'mu': 0, 'uacl': 71332791}, {'nm': '752BJ02 JAC T6 Муратбек Костанай', 'cls': 2, 'id': 25178517, 'mu': 0, 'uacl': 71332791}, {'nm': '754BJ02 JAC T6 Азат Актобе', 'cls': 2, 'id': 25178651, 'mu': 0, 'uacl': 71332791}, {'nm': '755BJ02 Outback Дмитрий Ускь-Кам', 'cls': 2, 'id': 25178431, 'mu': 0, 'uacl': 71332791}, {'nm': '756BJ02 JAC T6 Канат Талдыкорган', 'cls': 2, 'id': 25178388, 'mu': 0, 'uacl': 71332791}, {'nm': '757BJ02 Outback Думан Алматы', 'cls': 2, 'id': 25178405, 'mu': 0, 'uacl': 71332791}, {'nm': '760BJ02 JAC T6 Арыстан', 'cls': 2, 'id': 25178411, 'mu': 0, 'uacl': 71332791}, {'nm': '788AJ02 Forester Денис Костанай', 'cls': 2, 'id': 24406153, 'mu': 0, 'uacl': 71332791}, {'nm': '799AJ02 Forester Даурен Н.', 'cls': 2, 'id': 24406132, 'mu': 0, 'uacl': 71332791}, {'nm': '801AJ02 Terrano Рамиль', 'cls': 2, 'id': 24350993, 'mu': 0, 'uacl': 71332791}, {'nm': '802AJ02 Terrano Арыстан Койшекен', 'cls': 2, 'id': 24259637, 'mu': 0, 'uacl': 71332791}, {'nm': '803AJ02 Terrano Темирлан С.', 'cls': 2, 'id': 24350952, 'mu': 0, 'uacl': 71332791}, {'nm': '828YV02 Арон', 'cls': 2, 'id': 20556206, 'mu': 0, 'uacl': 71332791}, {'nm': '830AJ02 Lada Евгений Павлодар', 'cls': 2, 'id': 20556175, 'mu': 0, 'uacl': 71332791}, {'nm': '867YV02 Lada Ерлан Сарсен', 'cls': 2, 'id': 20556162, 'mu': 0, 'uacl': 71332791}, {'nm': '869CI02 Lada Архат М.', 'cls': 2, 'id': 20773564, 'mu': 0, 'uacl': 71332791}, {'nm': '870CI02 Largus Абурайхан К.', 'cls': 2, 'id': 20773559, 'mu': 0, 'uacl': 71332791}, {'nm': '871CI02 Ерлан Ж. Алматы', 'cls': 2, 'id': 20773562, 'mu': 0, 'uacl': 71332791}, {'nm': '911YV02 Largus Бахтияр М.', 'cls': 2, 'id': 20556163, 'mu': 0, 'uacl': 71332791}, {'nm': '912YV02 Forester Рысбек', 'cls': 2, 'id': 21250799, 'mu': 0, 'uacl': 71332791}, {'nm': '913YV02 Forester Самат', 'cls': 2, 'id': 21250816, 'mu': 0, 'uacl': 71332791}, {'nm': '914YV02 Forester Айдын', 'cls': 2, 'id': 21250730, 'mu': 0, 'uacl': 71332791}, {'nm': '915YV02 Forester Бакыт', 'cls': 2, 'id': 21250713, 'mu': 0, 'uacl': 71332791}, {'nm': '916YV02 Forester Айдос', 'cls': 2, 'id': 21250589, 'mu': 0, 'uacl': 71332791}, {'nm': '917YV02 Forester Ерлан', 'cls': 2, 'id': 20556194, 'mu': 0, 'uacl': 71332791}, {'nm': '918YР02 Outback Аман', 'cls': 2, 'id': 20556156, 'mu': 0, 'uacl': 71332791}, {'nm': '920YV02 Forester Шиковский В.', 'cls': 2, 'id': 21250616, 'mu': 0, 'uacl': 71332791}, {'nm': '921YP02 Forester Булашко А.', 'cls': 2, 'id': 20556155, 'mu': 0, 'uacl': 71332791}, {'nm': '925YV02 ARKANA Адильбек', 'cls': 2, 'id': 20556154, 'mu': 0, 'uacl': 71332791}, {'nm': '926YV02 ARKANA Ержан Ж.', 'cls': 2, 'id': 20556157, 'mu': 0, 'uacl': 71332791}, {'nm': 'свободный трекер', 'cls': 2, 'id': 20556214, 'mu': 0, 'uacl': 71332791}, {'nm': 'Трекер свободный 461DL02', 'cls': 2, 'id': 20556181, 'mu': 0, 'uacl': 71332791}, {'nm': 'Трекер свободный CAMRY 30 Махмуд', 'cls': 2, 'id': 20556191, 'mu': 0, 'uacl': 71332791}]}

In [2]:
import pandas as pd
df_nested_list = pd.json_normalize(result, record_path =['items'])
df_nested_list

                                    nm  cls        id  mu      uacl
0               01KG1187M SUZUKI Мурат    2  20556226   0  71332791
1                  01KG1219M LADA Едил    2  20556225   0  71332791
2         01KG1230M FORESTER Ешимов Н.    2  20556222   0  71332791
3                       01KG1346M LADA    2  20556221   0  71332791
4    012DL02 Largus Бакытжан Караганда    2  20556220   0  71332791
..                                 ...  ...       ...  ..       ...
104            925YV02 ARKANA Адильбек    2  20556154   0  71332791
105            926YV02 ARKANA Ержан Ж.    2  20556157   0  71332791
106                   свободный трекер    2  20556214   0  71332791
107           Трекер свободный 461DL02    2  20556181   0  71332791
108   Трекер свободный CAMRY 30 Махмуд    2  20556191   0  71332791

[109 rows x 5 columns]

# уақыт аралықтары 
o_date --> бұл басталу уақыты
rom_date --> бұл аяқталу уақыты
#керісіңше :)

In [3]:
rom_date=[
# 1635703200,
# 1635789600,
# 1635876000,
# 1635962400,
# 1636048800,
# 1636135200,
# 1636221600,
# 1636308000,
# 1636394400,
# 1636480800,
# 1636567200,
# 1636653600,
# 1636740000,
# 1636826400,
# 1636912800,
# 1636999200,
# 1637085600,
# 1637172000,
# 1637258400,
# 1637344800,
# 1637431200,
# 1637517600,
# 1637604000,
# 1637690400,
# 1637776800,
# 1637863200,
# 1637949600,
# 1638036000,
# 1638122400,
# 1638208800,
# 1638295200,
# 1638381600,
# 1638468000,
# 1638554400,
# 1638640800,
# 1638727200,
# 1638813600,
# 1638900000,
# 1638986400,
# 1639072800,
# 1639159200,
# 1639245600,
# 1639332000,
# 1639418400,
# 1639504800,
# 1639591200,
# 1639677600,
# 1639764000,
# 1639850400,
# 1639936800,
# 1640023200,
# 1640109600,
# 1640196000,
# 1640282400,
# 1640368800,
# 1640455200,
# 1640541600,
# 1640628000,
# 1640714400,
# 1640800800,
# 1640887200
#     ,
# 1652292000,
# 1652378400,
# 1652464800,
# 1652551200,
# 1652637600,
# 1652724000,
# 1652810400,
# 1652896800,
# 1652983200,
# 1653069600,
# 1653156000,
# 1653242400,
# 1653328800,
# 1653415200,
# 1653501600,
# 1653588000,
# 1653674400,
# 1653760800,
# 1653847200,
# 1653933600,
# 1654020000,
          
1654106400,
1654192800,
1654279200,
1654365600,
1654452000,
1654538400,
1654624800,
1654711200,
1654797600
]
rom_date

[1654106400,
 1654192800,
 1654279200,
 1654365600,
 1654452000,
 1654538400,
 1654624800,
 1654711200,
 1654797600]

In [4]:
o_date=[
# 1635789599,
# 1635875999,
# 1635962399,
# 1636048799,
# 1636135199,
# 1636221599,
# 1636307999,
# 1636394399,
# 1636480799,
# 1636567199,
# 1636653599,
# 1636739999,
# 1636826399,
# 1636912799,
# 1636999199,
# 1637085599,
# 1637171999,
# 1637258399,
# 1637344799,
# 1637431199,
# 1637517599,
# 1637603999,
# 1637690399,
# 1637776799,
# 1637863199,
# 1637949599,
# 1638035999,
# 1638122399,
# 1638208799,
# 1638295199,
# 1638381599,
# 1638467999,
# 1638554399,
# 1638640799,
# 1638727199,
# 1638813599,
# 1638899999,
# 1638986399,
# 1639072799,
# 1639159199,
# 1639245599,
# 1639331999,
# 1639418399,
# 1639504799,
# 1639591199,
# 1639677599,
# 1639763999,
# 1639850399,
# 1639936799,
# 1640023199,
# 1640109599,
# 1640195999,
# 1640282399,
# 1640368799,
# 1640455199,
# 1640541599,
# 1640627999,
# 1640714399,
# 1640800799,
# 1640887199,
# 1640973599
#     ,
# 1652378399,
# 1652464799,
# 1652551199,
# 1652637599,
# 1652723999,
# 1652810399,
# 1652896799,
# 1652983199,
# 1653069599,
# 1653155999,
# 1653242399,
# 1653328799,
# 1653415199,
# 1653501599,
# 1653587999,
# 1653674399,
# 1653760799,
# 1653847199,
# 1653933599,
# 1654019999,
# 1654106399,

1654192799,
1654279199,
1654365599,
1654451999,
1654538399,
1654624799,
1654711199,
1654797599,
1654883999
]
o_date

[1654192799,
 1654279199,
 1654365599,
 1654451999,
 1654538399,
 1654624799,
 1654711199,
 1654797599,
 1654883999]

In [5]:
# df_nested_list=df_nested_list['id']
# df_nested_list

In [6]:
#бұл код wialon-нан белгілі бір период аралыгын шыгарып береді күн-ай-жыл"пробел"уакыт 
from wialon import Wialon             
from wialon import WialonError
from datetime import datetime
import json
import pyodbc
import numpy as np
z=[]
from_date=rom_date
to_date=o_date

for j in range(len(from_date)):
    for i in df_nested_list['id']:
        try:
            qwe=[]
            wialon_api = Wialon()
            result = wialon_api.token_login(token='070b1b14f585912b9b172d65147bea8a35F9FEBE0D11F7F8D0436964F7A299DFF8E5E938')
            wialon_api.sid = result['eid']

            params = {"reportResourceId":20556144,
                    "reportTemplateId":1,
                    "reportObjectId":i,
                    "reportObjectSecId":0,
                    "interval":
                    {
                        "from":from_date[j],
                        "to":to_date[j],
                        "flags":0
                    }
                   }
            otchet = wialon_api.report_exec_report(**params)
             #print(otchet)
            wialon_api.core_logout()
        #     otchet['car_id']=i
            #otchet['car_name']=df_nested_list[nm]
            if otchet['reportResult']['msgsRendered']==1:
                if otchet['reportResult']['tables']!=[] and otchet['reportResult']['tables'][0]['label']=='Поездки':
                    #print(otchet['reportResult']['tables'])
                    z.append(otchet)
                    qwe.append(otchet['reportLayer']['units'][0]['id'])
                    qwe.append(datetime.fromtimestamp(otchet['reportResult']['tables'][0]['totalRaw'][1]['v']).strftime("%Y%m%d %H:%M:%S"))#time_start
                    qwe.append(datetime.fromtimestamp(otchet['reportResult']['tables'][0]['totalRaw'][4]['v']).strftime("%Y%m%d %H:%M:%S"))#time_end
                    qwe.append(otchet['reportResult']['tables'][0]['total'][5])#duration
                    qwe.append(pd.to_numeric(otchet['reportResult']['tables'][0]['totalRaw'][6]['v']))#mileage
                    qwe.append(pd.to_numeric(otchet['reportResult']['tables'][0]['totalRaw'][7]['v']))#max_speed
                    qn=pd.DataFrame(qwe)
                    qn=qn.transpose()
        #             print(qn)
                    conn = pyodbc.connect('Driver=SQL Server;Server=192.168.1.209;Database=L1_X;Trusted_Connection=yes;')
                    cursor = conn.cursor()
                    insertQuery = '''INSERT INTO [L1_X].[dbo].[WIALON_NEW] (ID_WIALON, START_TIME, END_TIME, DURATION, MILEAGE, MAX_SEED)
                            VALUES (?,convert(datetime,?),convert(datetime,?),convert(time,?), ?, ?)
                                    '''
                    try:
                        conn.autocommit = False
                        for t in qn.values.tolist():
    #                         t.append(i)
#                             i+=1
#                             print(t)
#                             print(len(t))
                            cursor.execute(insertQuery, t)
                    except Exception as e:
            #             print(t)

                        cursor.rollback()
                        print(e)
                        print('transaction rolled back')
                    else:
                        print('inserted successfully')
                        conn.commit()
                    finally:
                        conn.autocommit = True
                    df=otchet
        except WialonError as e:
                     print (e)

inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully

inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully
inserted successfully

In [166]:
qwe

[]

In [135]:
z

[]

In [136]:
otchet

{'reportResult': {'msgsRendered': 0,
  'stats': [],
  'tables': [],
  'attachments': []}}

In [137]:
qn

          0                  1                  2        3             4   5
0  20556220  20210901 09:25:12  20210901 17:03:53  2:10:37  46929.234984  69

In [ ]:
import pandas as pd
q = []
kugandar = []
for i in range(len(z['reportResult'])):
    w_otchet=[]
    try:
    #if 'unit_trips' in z['reportResult'][i]:
        w_otchet.append(z['car_id'][i])#id
        w_otchet.append(z['reportResult'][i]['tables'][0]['totalRaw'][1]['v'])#time_start
        w_otchet.append(z['reportResult'][i]['tables'][0]['totalRaw'][4]['v'])#time_end
        w_otchet.append(z['reportResult'][i]['tables'][0]['total'][5])#duration
        w_otchet.append(z['reportResult'][i]['tables'][0]['totalRaw'][6]['v'])#mileage
        w_otchet.append(z['reportResult'][i]['tables'][0]['totalRaw'][7]['v'])#max_speed
        q.append(w_otchet)
        print('Normal parse'+' '+str(i))
    except:
        kugandar.append(i)

In [ ]:
from datetime import datetime
qn=[]
for i in range(len(q)):
    dt_object=[]
    from_date = q[i][1]
    to_date = q[i][2]
    dt_from = datetime.fromtimestamp(from_date)
    dt_to = datetime.fromtimestamp(to_date)
    dt_object.append(pd.to_numeric(q[i][0]))
    dt_object.append(dt_from.strftime("%Y%m%d %H:%M:%S"))
    dt_object.append(dt_to.strftime("%Y%m%d %H:%M:%S"))
    dt_object.append(q[i][3])
    dt_object.append(pd.to_numeric(q[i][4]))
    dt_object.append(pd.to_numeric(q[i][5]))
    qn.append(dt_object)

In [38]:
import pandas as pd
df_nested_list = pd.json_normalize(otchet, ['reportResult'])
df_nested_list

TypeError: {'reportResult': {'msgsRendered': 1, 'stats': [], 'tables': [{'name': 'unit_trips', 'label': 'Поездки', 'grouping': {}, 'flags': 4496, 'rows': 6, 'level': 1, 'columns': 8, 'header': ['№', 'Начало', 'Нач. положение', 'Нач. координаты', 'Конец', 'Длительность', 'Пробег', 'Макс. скорость'], 'header_type': ['', 'time_begin', 'location_begin', 'coord_begin', 'time_end', 'duration', 'mileage', 'max_speed'], 'total': ['', '2021-09-01 03:25:12', '5 микрорайон, 18, Костанай, Костанайская обл., Казахстан', '53.171887, 63.591281', '2021-09-01 11:03:53', '2:10:37', '47 km', '69 km/h'], 'totalRaw': [{'v': 0, 'vt': 0}, {'v': 1630466712, 'vt': 30}, {'v': 0, 'vt': 1}, {'v': 0, 'vt': 0}, {'v': 1630494233, 'vt': 30}, {'v': 7837, 'vt': 40}, {'v': 46929.2349836, 'vt': 10}, {'v': 69, 'vt': 20}]}, {'name': 'unit_stops', 'label': 'Остановки', 'grouping': {}, 'flags': 4368, 'rows': 21, 'level': 1, 'columns': 5, 'header': ['№', 'Начало', 'Конец', 'Длительность', 'Положение'], 'header_type': ['', 'time_begin', 'time_end', 'duration', 'location'], 'total': ['', '2021-09-01 03:26:18', '2021-09-01 11:01:57', '0:15:57', ''], 'totalRaw': [{'v': 0, 'vt': 0}, {'v': 1630466778, 'vt': 30}, {'v': 1630494117, 'vt': 30}, {'v': 957, 'vt': 40}, {'v': -348201.3876, 'vt': 0}]}, {'name': 'unit_stays', 'label': 'Стоянки', 'grouping': {}, 'flags': 4368, 'rows': 7, 'level': 1, 'columns': 5, 'header': ['№', 'Начало', 'Конец', 'Длительность', 'Положение'], 'header_type': ['', 'time_begin', 'time_end', 'duration', 'location'], 'total': ['', '2021-09-01 00:00:57', '2021-09-01 17:59:55', '15:48:21', ''], 'totalRaw': [{'v': 0, 'vt': 0}, {'v': 1630454457, 'vt': 30}, {'v': 1630519195, 'vt': 30}, {'v': 56901, 'vt': 40}, {'v': -348201.3876, 'vt': 0}]}], 'attachments': []}, 'reportLayer': {'name': 'report unit_msgs', 'bounds': [53.1718864441, 63.5846672058, 53.275970459, 63.6757507324], 'units': [{'id': 20556220, 'msgs': {'count': 1799, 'first': {'time': 1630454457, 'lat': 53.1718864441, 'lon': 63.5912818909}, 'last': {'time': 1630519195, 'lat': 53.1724700928, 'lon': 63.5913658142}}, 'mileage': 46929.2349836, 'max_speed': 69}]}, 'layerCount': 1} has non list value {'msgsRendered': 1, 'stats': [], 'tables': [{'name': 'unit_trips', 'label': 'Поездки', 'grouping': {}, 'flags': 4496, 'rows': 6, 'level': 1, 'columns': 8, 'header': ['№', 'Начало', 'Нач. положение', 'Нач. координаты', 'Конец', 'Длительность', 'Пробег', 'Макс. скорость'], 'header_type': ['', 'time_begin', 'location_begin', 'coord_begin', 'time_end', 'duration', 'mileage', 'max_speed'], 'total': ['', '2021-09-01 03:25:12', '5 микрорайон, 18, Костанай, Костанайская обл., Казахстан', '53.171887, 63.591281', '2021-09-01 11:03:53', '2:10:37', '47 km', '69 km/h'], 'totalRaw': [{'v': 0, 'vt': 0}, {'v': 1630466712, 'vt': 30}, {'v': 0, 'vt': 1}, {'v': 0, 'vt': 0}, {'v': 1630494233, 'vt': 30}, {'v': 7837, 'vt': 40}, {'v': 46929.2349836, 'vt': 10}, {'v': 69, 'vt': 20}]}, {'name': 'unit_stops', 'label': 'Остановки', 'grouping': {}, 'flags': 4368, 'rows': 21, 'level': 1, 'columns': 5, 'header': ['№', 'Начало', 'Конец', 'Длительность', 'Положение'], 'header_type': ['', 'time_begin', 'time_end', 'duration', 'location'], 'total': ['', '2021-09-01 03:26:18', '2021-09-01 11:01:57', '0:15:57', ''], 'totalRaw': [{'v': 0, 'vt': 0}, {'v': 1630466778, 'vt': 30}, {'v': 1630494117, 'vt': 30}, {'v': 957, 'vt': 40}, {'v': -348201.3876, 'vt': 0}]}, {'name': 'unit_stays', 'label': 'Стоянки', 'grouping': {}, 'flags': 4368, 'rows': 7, 'level': 1, 'columns': 5, 'header': ['№', 'Начало', 'Конец', 'Длительность', 'Положение'], 'header_type': ['', 'time_begin', 'time_end', 'duration', 'location'], 'total': ['', '2021-09-01 00:00:57', '2021-09-01 17:59:55', '15:48:21', ''], 'totalRaw': [{'v': 0, 'vt': 0}, {'v': 1630454457, 'vt': 30}, {'v': 1630519195, 'vt': 30}, {'v': 56901, 'vt': 40}, {'v': -348201.3876, 'vt': 0}]}], 'attachments': []} for path reportResult. Must be list or null.

In [20]:
from datetime import date
today = date.today()
d1 = today.strftime("%Y-%m-%d")
today = datetime.fromtimestamp(today.strftime("%Y-%m-%d"))
print("Today's date:", today)
today
d1

TypeError: an integer is required (got type str)

In [25]:
# using calendar module
# using time module
import calendar;
import time;
  
# gmt stores current gmtime
gmt = time.gmtime()
print("gmt:-", gmt)
  
# ts stores timestamp
ts = calendar.timegm(gmt)
print("timestamp:-", ts)

gmt:- time.struct_time(tm_year=2022, tm_mon=6, tm_mday=10, tm_hour=8, tm_min=18, tm_sec=40, tm_wday=4, tm_yday=161, tm_isdst=0)
timestamp:- 1654849120

In [28]:
import calendar;
import time;
ts = calendar.timegm(time.gmtime())
print(ts)

1654849402

In [9]:
from datetime import date

today = date.today()

# dd/mm/YY
d1 = today.strftime("%d/%m/%Y")
print("d1 =", d1)

# Textual month, day and year	
d2 = today.strftime("%B %d, %Y")
print("d2 =", d2)

# mm/dd/y
d3 = today.strftime("%m/%d/%y")
print("d3 =", d3)

# Month abbreviation, day and year	
d4 = today.strftime("%b-%d-%Y")
print("d4 =", d4)

d1 = 10/06/2022
d2 = June 10, 2022
d3 = 06/10/22
d4 = Jun-10-2022

In [13]:
int(datetime.datetime.strptime(date.today(), '%d/%m/%Y').strftime("%s"))
today

AttributeError: type object 'datetime.datetime' has no attribute 'datetime'